# Welcome to the Capture the Castle Configuration

# set the text for the game scoreboard (uses fast board api)
gameScoreboard:
  - "monkey"
  - "balls"
  - "nuts"
king:
  name: "Bozo the Clown"
  health: 1