name: CaptureTheCastle
version: ${project.version}
main: me.lebryant.capturethecastle.CaptureTheCastle
authors: [ LebryantJohnson ]
softdepend: [PlaceholderAPI]
commands:
  ccadmingui:
    description: open command gui
    usage: /<command>
    permission: cc.admin
  capturethecastle:
    description: basic command
    usage: /<command>
  setlobby:
    description: sets the lobby location for the minigame
    usage: /<command>
    permission: cc.admin
  lobby:
    description: tp to lobby
    usage: /<command>
  start:
    description: starts game no matter what
    usage: /<command>
    permission: cc.admin
  setarenalocation:
    description: set arena location
    usage: /<command>
    permission: cc.admin
  join:
    description: join arena
    usage: /<command>
  leave:
    description: leave arena
    usage: /<command>
  createccarena:
    description: create arena
    usage: /<command>
    permission: cc.admin
  removeccarena:
    description: remove arena
    usage: /<command>
    permission: cc.admin